### ISSUE TITLE
Not able to delete records from aerospike after ttl expiration.

### ISSUE THREAD

**Issue by bindra888** [vlad-aleksandrov/spring-cache-aerospike#1]
If I create a cache and give it some ttl to expire. In AerospikeCacheManager class when it creates a cache it takes argument as timeToLive, but never uses this. 
If I manually set this, then again it does not evict the cache of the data after ttl.

Is there any way to delete data from cache after ttl expiration?

Below code does this, if set:
  private AerospikeTemplate buildAerospikeTemplate(final String namespace, final String setname, int timeToLive) {
        final AerospikeTemplate template = new AerospikeTemplate();
        template.setAerospikeClient(aerospikeClient);
        template.setAerospikeAsyncClient(aerospikeAsyncClient);
        template.setNamespace(namespace);
        template.setSetname(setname);
        template.setExpiration(timeToLive);
        template.init();
        return template;
    }

**Comment by shaileshmishra008** [comment]
Though it has been ~2.5 yrs, but may be useful for others. I [forked the repo](https://github.com/shaileshmishra008/spring-cache-aerospike) and uploaded the fixes along with spring boot 2 and aerospike 4.1.5 support.

there is a small bug in AerospikeCacheManager class. which does not call the AerospikeTemplate.init method before handing it to AerospikeCache class.

Following change make (<===) it work:
```
public AerospikeCache createCache(final String name, int timeToLive) {
        Assert.hasText(name, "Cache name can't be empty");
        AerospikeTemplate template = null;
        if (name.contains(":")) {
            // namespace explicitly defined
            String[] nameParts = name.split(":", 2);
            template = buildAerospikeTemplate(nameParts[0], nameParts[1]);
        } else {
            template = buildAerospikeTemplate(defaultNamespace, name);
        }
        template.setExpiration(timeToLive);
        //Init the template before passing it to cache. <<===============================
        template.init();
        final AerospikeCache cache = new AerospikeCache(template, serializer);
        caches.put(cache.getName(), cache);
        return cache;

    }
```
